language: objective-c
osx_image: xcode7.1
script:
  - xcodebuild test -project Calculator/Calculator.xcodeproj -scheme CalculatorTests -sdk iphonesimulator9.1 -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)