language: objective-c
osx_image: xcode7.1
script: 
  - xcodebuild -project Calculator/Calculator.xcodeproj -scheme CalculatorTests test -sdk iphonesimulator9.1 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
before_install:
  - pip install codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)