language: objective-c
osx_image: xcode7.1
script: - xcodebuild -scheme CalculatorTests -project Calculator/Calculator.xcodeproj -sdk iphonesimulator9.1 -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' test
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# Only build PRs and pushes to master
branches:
  only:
    - master