language: objective-c
osx_image: xcode7.1
before_install:
  - pip install codecov
script: 
  - xctool -project Calculator/Calculator.xcodeproj -scheme CalculatorTests build test -sdk iphonesimulator9.1 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)